### ISSUE TITLE
Videos not changing when matcher updates

### ISSUE THREAD

**Issue by rtablada** [sbatson5/ember-wistia#16]
I'm not sure if this is an issue with the underlying Wistia API or if it is an issue with Ember bindings, but I've found that videos do not change when the `matcher` is changed.

I'm not sure if you've run into this issue as well?

**Comment by sbatson5** [comment]
I think this is just how wistia works.  When the `div` renders, the matcher is put in the class name--Wistia then uses that class name to find the right video and render it. At that point, the matcher isn't used anymore, so updating it won't trigger anything.  I haven't run into this myself, but I suppose we could force the component to rerender if the `matcher` updates.

I can try to write a PR to see if it is that simple later in the week.

**Comment by sbatson5** [comment]
Think I have a fix. Just need to write some tests:

![switch-video](https://user-images.githubusercontent.com/881981/35770826-01932918-08f1-11e8-9628-fe628f4a4f56.gif)
